RegisterNetEvent('playerSpawned')
AddEventHandler('playerSpawned', function()
    Wait(3000) 
    TriggerServerEvent('vorp:checkAndFixVW')
end)

RegisterNetEvent('vorp:clientDebug')
AddEventHandler('vorp:clientDebug', function(msg)
    print(msg)
end)
